version: "3.8"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak-dms
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres-db
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
    ports:
      - "8180:8080"
    depends_on:
      - postgres-db
    networks:
      - keycloak-net

  postgres-db:
    image: postgres:14
    container_name: postgres-db-keycloak
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - keycloak-net

networks:
  keycloak-net:
    driver: bridge

volumes:
  keycloak_db_data:
